#-------------------------------
# General Site Settings

title: Joey Lim
logo: 
author: themefisher
description: Joey's portfolio
email: limjoey@protonmail.com
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hello, I’m Joey! <br> Android App Developer <br> Tech Enthusiast

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/joeyllp/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I mainly develop Android Apps but I am also familiar with cloud technologies like AWS. <br> I enjoy learning new techy things and I'm currently learning game development and trying to blog about tech on the side!

blurb-btn-link: '/about'
blurb-btn-name: Learn more...


# About Page


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Native Android App Development, color: '#3DDC84', value: '100%'}
- {name: Mobile UI/UX Design, color: '#bdecf6', value: '70%'}
- {name: NodeJS Development, color: '#303030', value: '60%'}
- {name: Game Development, color: '#ffbcaa', value: '40%'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Diploma in Information Technology, date: '2020 - present', organization: 'Temasek Polytechnic'}
- {name: GCE 'O' Level Certificate, date: '2016 - 2019', organization: 'Loyang View Secondary School'}

#-------------------------------
# Achievements Section

achievements-title: Achievements
achievement:
- {name: WorldSkills Singapore 2021, date: '2021', award: 'Gold'}
- {name: TP-Essilor Innovation Challenge, date: '2021', award: 'First Runner-Up'}


# Portfolio Page
portfolio-label:
- {
    title : "UI Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
